### ISSUE TITLE
migrate Resolver v1 to v2 - API calls

### ISSUE THREAD

**Issue by medbensalem** [cloudreach/sceptre#613] opened 2019-01-22 16:06 UTC
Hi,

I'm migrating for Sceptre v1 to v2 and I'm having some troubles adapting some custom resolvers.
For example, the script below is retrieving ECR Images tags depending on certain conditions and entry variables we are providing, this is working fine is V1 but because a lot of API calls have changed in V2, the script is now broken.

So my question is what is the equivalent to this python line with the new API syntax:

```python
self.environment_config.get('user_variables', {}).get('Tag')

self.environment_config['user_variables']['Tag']
```

Where "Tag" is a enty variable we are passing.
So the scpetre commad we are running is:

```bash
sceptre --var "Tag=tag-value-x" launch stg  #For Example
```

Please, could you also direct me to the right documentation describing the new API, I was not able to find something accurate.

Please find below the full script for more context.

Thank you for this great tool.

```python
from pprint import pprint
import re
from sceptre.resolvers import Resolver


class GetEcrTag(Resolver):

    def __init__(self, *args, **kwargs):
        super(GetEcrTag, self).__init__(*args, **kwargs)

    def get_prev_production_image(self, ecr_client, repository_name, tag_filter="production-.*"):
        """
        This function return the previous image used in production if exist
        from AWS ECR repository

        :param ecr_client:
        :param tag_filter:
        :param repository_name:

        """
        production_tags = []
        all_images = self.get_sorted_images(ecr_client, repository_name)
        r = re.compile(tag_filter)

        for imageTags in all_images:
            if imageTags.get('imageTags'):
                filtered_tags = list(filter(r.match, imageTags['imageTags'])).copy()
                for tag in filtered_tags:
                    production_tags.append(tag)

        if len(production_tags) >= 2:
            tag = self.resolve_image_tag(ecr_client, repository_name, production_tags[1])
            self.logger.info("ATTENTION: Rollback is enabled")
            return tag
        else:
            raise Exception("Error - not tagged images availabe")


    def resolve_image_tag(self, ecr_client, repository_name, search_tag):
        """
        This function return the tag with git hash resolved by the search_tag
        from AWS ECR repository

        :param ecr_client:
        :param repository_name:
        :param tag_filter:

        """
        tag = []
        all_images = self.get_sorted_images(ecr_client, repository_name)
        r = re.compile('^[a-zA-Z0-9_]{8}$') #match 8 alphanumeric chars

        for imageTags in all_images:
            if imageTags.get('imageTags'):
                if search_tag in imageTags['imageTags']:
                    tag = list(filter(r.match, imageTags['imageTags']))

        if not tag:
            raise Exception("Error - not tagged images availabe")
        else:
            return tag[0]

    @staticmethod
    def get_sorted_images(ecr_client, repository_name):
        """
        This function return a list of images sorted by date ASC
        from AWS ECR repository

        :param repository_name:
        :param ecr_client:
        """
        images = []
        describeimage_paginator = ecr_client.get_paginator('describe_images')

        for page in describeimage_paginator.paginate(repositoryName=repository_name):
            for image in page['imageDetails']:
                images.append(image)

        images.sort(key=lambda k: k['imagePushedAt'], reverse=True)
        return images

    def resolve(self):
        if self.environment_config.get('user_variables', {}).get('rollback'):
            rollback = self.environment_config['user_variables']['rollback']
            if rollback.lower() == 'true':
                rollback = True
            else:
                rollback = False
        else:
            rollback = False

        if self.argument:
            environment = self.stack_config['parameters']['Environment']

            session = self.connection_manager.boto_session
            client = session.client("ecr")

            if rollback and environment == 'prd':
                # resolve the previous production tagged image
                tag = self.get_prev_production_image(client, self.argument)
                self.logger.info("Deploing the previous production image: " + tag)
                return tag
            else:
                # use the Tag variable passed
                if self.environment_config.get('user_variables', {}).get('Tag'):
                    # deploy the specified hash tag into the user variable
                    tag = self.environment_config.get('user_variables', {}).get('Tag')
                    self.logger.info("Deploing the passed image: " + tag)
                    return self.environment_config['user_variables']['Tag']
                else:
                    # resolve the hash tag by production or staging env
                    if environment == 'stg':
                        self.logger.info(self.argument + ": Resolving the latest staging image hash")
                        tag = self.resolve_image_tag(client, self.argument, "latest")
                        self.logger.info(self.argument + ": Resolved the image hash: " + tag)
                        return tag
                    if environment == 'prd':
                        self.logger.info(self.argument + ": Resolving the latest production image hash")
                        tag = self.resolve_image_tag(client, self.argument, "production")
                        self.logger.info(self.argument + ": Resolved the image hash: " + tag)
                        return tag

```

**Comment by zaro0508** [comment] 2019-01-29 19:07
hmm.  sceptre V2 doesn't seem to provide access to a `user_variables` from resolvers or hooks.  This seems like a bug to me.

Although I'm wondering if this might be by design because I think you can pass user_variables to your resolver with a var reference i.e. `{{ var.Tag }}`  

In your case I think it would work like this..
```
parameters:
  mytag: ! get_ecr_tag {{ var.Tag }}
```

**Comment by ngfgrant** [comment] 2019-01-29 19:12
I think the tag thing in particular is a bug related to #426 and/or https://github.com/cloudreach/sceptre/issues/562

**Comment by medbensalem** [comment] 2019-01-30 10:10
For the moment I was able to hack this by defining "stack_group_config" variables and make their values loaded/overwritten by the CLI. 
Example:
```
# On the config.yaml - I define a new variable like below
ecr_tag: {{ var.Tag | default("latest") }} 

# On the Resolver/Hook - I reteive the variable by loading the  stack_group_config
# In the case below the variable value will be defaulted to "latest"
tag = self.stack.stack_group_config.get('ecr_tag')

# From the CLI - If I need to overwrite the variable I just need to pass the variable from the CLI
sceptre --var "Tag=tag-value-x" launch stg
```
Like mentioned before this seems more like a hack, I hope this bug get fixed soon.
Please let me know what do you guys think.

**Comment by zaro0508** [comment] 2019-01-30 18:31
I agree that it's a hack,  nice workaround though.  I think `user_variables` should be directly accessible from the any plugin.  @medbensalem maybe you can create an issue for this?

**Comment by medbensalem** [comment] 2019-01-31 10:10
Yep, you are totally right, I have created an issue to track this #618.
Thank you guys for your time.

**Comment by ngfgrant** [comment] 2019-02-28 09:17
Closing as this is tracked in #618

**Closed by ngfgrant** 2019-02-28 09:17 UTC
