### ISSUE TITLE
CreateStack cannot be used with templates containing Transforms.

### ISSUE THREAD

**Issue by eikenb** [cloudreach/sceptre#485] opened 2018-10-19 19:46 UTC
Trying to create a stack with an AWS::Include FN::Transform in it and am getting this error.

An error occurred (ValidationError) when calling the CreateStack operation: CreateStack cannot be used with templates containing Transforms.

This might be the same as #421 but that one is specifically about updates where this is create.

**Comment by ngfgrant** [comment] 2018-12-09 09:02
Duplicate of #421

**Closed by ngfgrant** 2018-12-09 09:02 UTC
