### ISSUE TITLE
If stack config is invalid sceptre fails in a non-obvious way

### ISSUE THREAD

**Issue by JGjorgji** [cloudreach/sceptre#248] opened 2017-11-06 16:20 UTC
If i leave an empty `something.yaml` file in the config directory sceptre fails with this error:

```
Traceback (most recent call last):
  File "/home/gjorgji/.local/bin/sceptre", line 11, in <module>
    load_entry_point('sceptre==1.3.1', 'console_scripts', 'sceptre')()
  File "/home/gjorgji/.local/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/gjorgji/.local/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/gjorgji/.local/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gjorgji/.local/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gjorgji/.local/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/gjorgji/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gjorgji/.local/lib/python3.6/site-packages/sceptre/cli.py", line 96, in decorated
    return func(*args, **kwargs)
  File "/home/gjorgji/.local/lib/python3.6/site-packages/sceptre/cli.py", line 327, in delete_env
    response = env.delete()
  File "/home/gjorgji/.local/lib/python3.6/site-packages/sceptre/environment.py", line 140, in delete
    threading_events = self._get_threading_events()
  File "/home/gjorgji/.local/lib/python3.6/site-packages/sceptre/helpers.py", line 49, in decorated
    with ThreadPoolExecutor(max_workers=num_environments) as executor:
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 97, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
```

It should raise an error that there's an invalid stack config instead of failing like this, this seems related to #163

**Comment by theseanything** [comment] 2017-11-06 18:13
Hmm interesting! Agree their needs to a be a better error message. What command did you use?

**Comment by JGjorgji** [comment] 2017-11-07 06:07
This happened with the launch-env/delete-env commands.

**Comment by theseanything** [comment] 2017-11-08 14:36
Ah I'm unable to replicate this error - could you give a me a directory tree and version of sceptre?

**Comment by ngfgrant** [comment] 2017-11-13 17:02
Hi @JGjorgji 

I have also tried to replicate this error and have been unable to reproduce. I have tested with Python versions 2.7.14 and 3.6.1. 

My directory structure:

sceptre/
...
- > config/
    - > something.yaml 
    - > dev/

I am testing with valid templates.  

Looking at the stack trace, sceptre is trying to treat your Environment as a "non-leaf" environment. and we could probably improve the error catching and message in cli.py. As @seanrankine has mentioned would be great to get a bit more detail on your setup so we can help resolve this for you.

**Comment by ngfgrant** [comment] 2017-11-13 19:04
looking through some closed issues. #163  and #190  might have been related to this. Potentially the max_workers=0 error was fixed in ```stack.py``` but not in ```helpers.py```?

**Comment by theseanything** [comment] 2017-11-14 16:21
Think the issues above are related to this. Closing for now.

**Closed by theseanything** 2017-11-14 16:21 UTC
Labels: awaiting reply

**Comment by JGjorgji** [comment] 2017-11-14 16:38
Sorry for the late reply, I think I've narrowed down the case where this happens. I use symlinks to link to common configs as most of the configs are pretty static, if the symlink is to a non-existant file but a valid config name this happens.
