### ISSUE TITLE
Custom stack name rules

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#147] opened 2017-06-20 15:42 UTC
Currently the CloudFormation stack name is generated from the `project code + filepath` - (unless stack_name is specified). It would be useful to be able to state a rule to describe how stack names are generated. For example `project_code + region + "another-string" + filepath`.

Suggested implementation:
Having a property in Environment Config in which a rule can be specified as Python expression.
e.g.
```
project_code: example
region: eu-west-1
stack_name_rule:  [project_code, "another_string", path]  # this list is joined together with "-"
```
or
e.g.
```
project_code: example
region: eu-west-1
stack_name_rule:  "-".join([project_code, region].extend(path))
```
There is the potential issue whereby stack names are the same . However we already have this issue when using the `stack_name` property in a stack config.

This feature prevents having`stack_name` in every stack where you want a different naming convention.

**Comment by theseanything** [comment] 2017-06-20 15:54
Personally - I want to use this functionality to achieve the ability to organising stack by region but not have it present in the stack-name. For example - my config folder is like below:

```
├── base
├── config.yaml
├── eu-west-1
│   ├── audit
│   │   ├── alarm.yaml
│   ├── config.yaml
│   └── networking
│       └── vpc.yaml
├── global
│   ├── audit
│   │   ├── inactive-users-rule.yaml
│   ├── config.yaml
│   └── iam
│       ├── audit-roles.yaml
│       ├── networking-roles.yaml
└── us-east-1
    ├── audit
    │   ├── alarms.yaml
    ├── config.yaml
    └── networking
        └── vpc.yaml
```

I would like to create an environment to spin up resources in each of the regions. But I don't want `eu-west-1` or `global` or `us-east-1` to appear in the stack name. e.g. `example-base-networking-vpc`

**Comment by ianburrell** [comment] 2017-09-28 21:47
It should be possible to template the stack_name.

The problem is that a few of the things would want to use for stack names aren't available in template: environment config, region, or file name. If they were could do:

`stack_name: {{ environment_path|join("-") ~ "-" ~ file_name }}`

`stack_name: {{ environment_config.project_code ~ "-" environment_config.region ~ "-" ~ file_name }}`

Could even put in default template that gets included for every stack: 

`{% include 'defaults.yaml' %}`

**Comment by JuanCanham** [comment] 2017-11-13 16:52
Why `stack_name_rule` instead of `stack_name`?
`stack_name` would make it easier to grep repos and mean less config keys to remember

**Comment by ngfgrant** [comment] 2018-02-15 17:07
Not a priority or a frequent request. Closing for now.

**Closed by ngfgrant** 2018-02-15 17:07 UTC
Labels: feature request
