### ISSUE TITLE
sceptre v2: maximum recursion depth exceeded exception

### ISSUE THREAD

**Issue by ryanpagel** [cloudreach/sceptre#550] opened 2018-12-10 04:03 UTC
I'm getting the following exception when running a `sceptre update`:

![image](https://user-images.githubusercontent.com/805791/49710314-3688cc80-fbfe-11e8-985a-e35dcfc34ad8.png)

**Comment by ngfgrant** [comment] 2018-12-10 09:22
Hey @ryanpagel

This has come up for a couple of people when migrating across to v2. It is likely to be a error in the config. Is there anyway you can share more information about the config/stacks?

**Comment by ryanpagel** [comment] 2018-12-21 07:04
What kind of information are you looking for?  At a high level we have config/dev, config/test, and config/prod.  Each environment has a few dozen stacks.  Is there anything I can look into that might cause a config error?  Here's the latest error message:
![image](https://user-images.githubusercontent.com/805791/50329319-594b9880-04bc-11e9-8ce0-8cab22409f75.png)

**Comment by priorax** [comment] 2018-12-30 04:34
I know I had the same issue and found that #https://github.com/cloudreach/sceptre/issues/558 was the cause of my issues.
I had a user_data that was trying to get output of another stack and pass it into a stack that was based on Troposphere, once I moved this to being a parameter there was no issue and it worked fine.

Are you doing anything similar to this?

**Comment by ryanpagel** [comment] 2018-12-31 19:54
I'm using !stack_output_external but not !stack_outuput.

**Comment by priorax** [comment] 2019-01-02 10:56
For the sake of seeing if it's a related bug, if you move those resolvers to being parameters instead of user data do you get the same exception?

**Comment by ryanpagel** [comment] 2019-01-07 20:11
The challenge here is that we have dozens of stacks that are using `!stack_output_external`.  There's not an easy way to change everything over to using parameters instead of `sceptre_user_data`.

**Comment by pha6d** [comment] 2019-01-08 07:59
in a custom resolver, resolve method, retrieving a connection_manager instance like: `self.stack.template.connection_manager` leads to 
` File "/usr/lib/python2.7/site-packages/sceptre/helpers.py", line 53, in func_on_instance
    if isinstance(value, cls):
  File "/usr/lib64/python2.7/abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
RuntimeError: maximum recursion depth exceeded`

forcing me to retrieve a new one like `connection_manager = ConnectionManager(self.stack.region, self.stack.profile, self.stack.name)`

**Comment by m1keil** [comment] 2019-02-04 02:02
This issue happens with both stack_output & stack_output_external resolvers.

**Comment by ngfgrant** [comment] 2019-04-16 13:54
Closing to track on #558.

**Closed by ngfgrant** 2019-04-16 13:54 UTC
Labels: priority: important, type: bug
