### ISSUE TITLE
hook fails when var-file used

### ISSUE THREAD

**Issue by craighurley** [cloudreach/sceptre#410] opened 2018-06-19 05:17 UTC
My hook fails when I use a var-file.  It succeeds otherwise.  Can someone please advise on how to fix/workaround?

# Version

```
$ sceptre --version
Sceptre, version 1.3.4
```

# Reproduction

## Files

`vars/prod.yaml`:

```yaml
VpcCidr: 172.20.0.0/16
SubnetCount: 256
SubnetMaskSize: 8
```

`config/prod/network.yaml`:

```yaml
template_path: templates/network.yaml
stack_tags:
  Application: {{ environment_config.project_code }}
  Environment: {{ environment_config.environment }}
  Owner: {{ environment_config.owner }}
parameters:
  Prefix: {{ environment_config.project_code }}
  Environment: {{ environment_config.environment }}
  VpcCidr: '{{ var.VpcCidr }}'
  SubnetCount: '{{ var.SubnetCount }}'
  SubnetMaskSize: '{{ var.SubnetMaskSize }}'

hooks:
  after_create:
    - !set_stack_termination_protection 'enabled'
  before_delete:
    - !set_stack_termination_protection 'disabled'
```

## ERROR output

```
$ sceptre --var-file=vars/prod.yaml launch-env prod
[2018-06-19 17:01:24] - sceptre.stack - prod/network - Launching stack
[2018-06-19 17:01:24] - sceptre.stack - prod/network - Stack is in the PENDING state
[2018-06-19 17:01:24] - sceptre.stack - prod/network - Creating stack
[2018-06-19 17:01:25] - sceptre.stack - 2018-06-19T05:01:25+00:00 prod/network ch-prod-network AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2018-06-19 17:01:29] - sceptre.stack - 2018-06-19T05:01:28+00:00 prod/network VPC AWS::EC2::VPC CREATE_IN_PROGRESS
[2018-06-19 17:01:29] - sceptre.stack - 2018-06-19T05:01:28+00:00 prod/network VPC AWS::EC2::VPC CREATE_IN_PROGRESS Resource creation Initiated
[2018-06-19 17:01:50] - sceptre.stack - 2018-06-19T05:01:46+00:00 prod/network VPC AWS::EC2::VPC CREATE_COMPLETE
[2018-06-19 17:01:50] - sceptre.stack - 2018-06-19T05:01:48+00:00 prod/network ch-prod-network AWS::CloudFormation::Stack CREATE_COMPLETE
[2018-06-19 17:01:54] - sceptre.environment - Stack prod/network failed to launch
Traceback (most recent call last):
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/environment.py", line 252, in _manage_stack_build
    status = getattr(stack, command)()
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/stack.py", line 281, in launch
    status = self.create()
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/hooks/__init__.py", line 71, in decorated
    execute_hooks(self.hooks.get("after_" + func.__name__))
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/hooks/__init__.py", line 57, in execute_hooks
    hook.run()
  File "/Users/craig.hurley/Projects/bulletproof/stack-dotgolf-test/hooks/stacks.py", line 26, in run
    cf_stack_name = stack.external_name
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/stack.py", line 177, in external_name
    self._external_name = self.config.get(
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/stack.py", line 101, in config
    self.environment_config
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/config.py", line 191, in read
    config = get_config(path)
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/sceptre/config.py", line 181, in get_config
    environment_config=environment_config
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/craig.hurley/.pyenv/versions/3.6.5/envs/sceptre/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/craig.hurley/Projects/bulletproof/stack-dotgolf-test/config/prod/network.yaml", line 11, in top-level template code
    SubnetMaskSize: '{{ var.SubnetMaskSize }}'
jinja2.exceptions.UndefinedError: 'None' has no attribute 'VpcCidr'
```

# Notes

If I change `config/prod/network.yaml` to use defaults for what would normally be passed in from the var-file, the hook works:

```yaml
template_path: templates/network.yaml
stack_tags:
  Application: {{ environment_config.project_code }}
  Environment: {{ environment_config.environment }}
  Owner: {{ environment_config.owner }}
parameters:
  Prefix: {{ environment_config.project_code }}
  Environment: {{ environment_config.environment }}
  VpcCidr: '{{ var.VpcCidr | default("172.21.0.0/16") }}'
  SubnetCount: '{{ var.SubnetCount | default("256") }}'
  SubnetMaskSize: '{{ var.SubnetMaskSize | default("8") }}'

hooks:
  after_create:
    - !set_stack_termination_protection 'enabled'
  before_delete:
    - !set_stack_termination_protection 'disabled'
```

SUCCESS output:

```
$ sceptre --var-file=vars/prod.yaml launch-env prod
[2018-06-19 16:59:29] - sceptre.stack - prod/network - Launching stack
[2018-06-19 16:59:29] - sceptre.stack - prod/network - Stack is in the PENDING state
[2018-06-19 16:59:29] - sceptre.stack - prod/network - Creating stack
[2018-06-19 16:59:30] - sceptre.stack - 2018-06-19T04:59:30+00:00 prod/network ch-prod-network AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2018-06-19 16:59:34] - sceptre.stack - 2018-06-19T04:59:33+00:00 prod/network VPC AWS::EC2::VPC CREATE_IN_PROGRESS
[2018-06-19 16:59:34] - sceptre.stack - 2018-06-19T04:59:34+00:00 prod/network VPC AWS::EC2::VPC CREATE_IN_PROGRESS Resource creation Initiated
[2018-06-19 16:59:55] - sceptre.stack - 2018-06-19T04:59:51+00:00 prod/network VPC AWS::EC2::VPC CREATE_COMPLETE
[2018-06-19 16:59:55] - sceptre.stack - 2018-06-19T04:59:53+00:00 prod/network ch-prod-network AWS::CloudFormation::Stack CREATE_COMPLETE
[2018-06-19 16:59:59] - sceptre.hooks - Setting termination protection of stack 'ch-prod-network' to 'enabled'
```

---

# Hook

The hook in `hooks/stacks.py` and is as follows:

```py
"""
Provide utility hooks for operating on stacks.
"""

from sceptre.hooks import Hook
from sceptre.environment import Environment

class SetStackTerminationProtection(Hook):
    """
    Enable/disable stack termination protection.
    """

    ALLOWED_ARG_VALUES = ['enabled', 'disabled']

    def __init__(self, *args, **kwargs):
        super(SetStackTerminationProtection, self).__init__(*args, **kwargs)

    def run(self):
        argument = (self.argument if self.argument else '').lower()

        assert argument in self.ALLOWED_ARG_VALUES, \
            "As the argument for !set_stack_termination_protection, please choose one of {0}".format(self.ALLOWED_ARG_VALUES)

        environment = Environment(self.environment_config.sceptre_dir, self.environment_config.environment_path)
        stack = environment.stacks[self.stack_config.name]
        cf_stack_name = stack.external_name

        enable = argument == 'enabled'

        self.logger.info(
            "Setting termination protection of stack '%s' to '%s'",
            cf_stack_name, argument)

        self.connection_manager.call('cloudformation', 'update_termination_protection',
                                     kwargs={
                                         'StackName': cf_stack_name,
                                         'EnableTerminationProtection': enable
                                     })
```

**Comment by ngfgrant** [comment] 2018-06-22 09:54
Hi @craighurley 

Just quickly looking at the CLI code for this. It looks like the CLI is expecting a file rather than a path to a file. Could you experiment with moving the var file up one level and running 

```sceptre --var-file=prod.yaml launch-env prod```

It might not be the root cause but it is a starter for 10. I'll dig deeper on this in a bit.

**Comment by ngfgrant** [comment] 2018-06-22 10:01
Ah actually - can you try using `--var-file` without the `=` (keep the directory structure as you originally had):

```sceptre --var-file prod.yaml launch-env prod```

I think this might be a case of outdated docs.

**Comment by ngfgrant** [comment] 2018-06-22 12:45
Hi @craighurley 

Ok so looking into this it looks like there is a limitation in the information we make accessible within Hooks. 

Basically, it looks like the main thing you are trying to get the `stack.external_name`. In doing so, you create a stack and environment. Unfortunately, the methods that this triggers means you don't have access to the user_variables that you have passed in on the CLI. Hence, the error `jinja2.exceptions.UndefinedError: 'None' has no attribute 'VpcCidr'`.

For us, we need to look at providing ways to access `stack.external_name` in Hooks without creating new Environments and Stacks. 

There is a bit of a hack that you can apply in the meantime. 

The method: `_load_environments()`in `Environment.py` allows you to pass a 3rd parameter called `options`, which is a dictionary. In this dictionary all you need to do is pass in the names of the user_variables you have, with empty values and that will resolve the issues you are having. 

```
environment = Environment(
    self.environment_config.sceptre_dir, 
    self.environment_config.environment_path, 
    {
        'user_variables': {
        'VpcCidr': '',
        'SubnetCount': '',
        'SubnetMaskSize': ''
    }
})
```

**Comment by ngfgrant** [comment] 2019-05-31 10:47
Closing as v1 issue which we won't fix as EOL. Should work in v2?

**Closed by ngfgrant** 2019-05-31 10:47 UTC
Labels: type: question
