### ISSUE TITLE
Wait for for stacks to be created when resolving

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#38] opened 2017-02-10 20:03 UTC
My terminal crashed mid way through launching an environment, so I ran the command to launch the environment again, however hit an resolver error. The reason for this was that stacks were still in a "create_in_progress" state and sceptre didn't wait for "create_complete" to resolve outputs for a dependee template.

```
[seanrankine:.../Project/project-infrastructure]$ sceptre launch-env prod/cybermation
[2017-02-10 14:55:28] - sceptre.stack - prod/cybermation/security-groups - Launching stack
[2017-02-10 14:55:28] - sceptre.stack - prod/cybermation/iam-role - Launching stack
[2017-02-10 14:55:33] - sceptre.stack - prod/cybermation/iam-role - Stack is in the CREATE_COMPLETE state
[2017-02-10 14:55:33] - sceptre.stack - prod/cybermation/iam-role - Updating stack
[2017-02-10 14:55:33] - sceptre.stack - prod/cybermation/security-groups - Stack is in the CREATE_COMPLETE state
[2017-02-10 14:55:33] - sceptre.stack - prod/cybermation/security-groups - Updating stack
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/security-groups - No updates to perform.
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/iam-role - No updates to perform.
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/iam-instance-profile - Launching stack
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/iam-instance-profile - Stack is in the CREATE_IN_PROGRESS state
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/iam-instance-profile - Stack action is already in progress state and cannot be updated
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/ec2-instances - Launching stack
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/ec2-instances - Stack is in the PENDING state
[2017-02-10 14:55:34] - sceptre.stack - prod/cybermation/ec2-instances - Creating stack
[2017-02-10 14:55:35] - sceptre.environment - Stack prod/cybermation/ec2-instances failed to launch
Traceback (most recent call last):
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/environment.py", line 244, in _manage_stack_build
    status = getattr(stack, command)()
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/helpers.py", line 79, in decorated
    return func(self, *args, **kwargs)
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/stack.py", line 273, in launch
    status = self.create()
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/hooks/__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/helpers.py", line 79, in decorated
    return func(self, *args, **kwargs)
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/stack.py", line 193, in create
    "Parameters": self._format_parameters(self.parameters),
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/resolvers/__init__.py", line 72, in __get__
    return self.resolve_values(getattr(instance, self.name))
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/resolvers/__init__.py", line 91, in resolve_values
    attr[key] = value.resolve()
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/resolvers/stack_output.py", line 119, in resolve
    return self._get_output_value(stack_name, self.output_key)
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/resolvers/stack_output.py", line 34, in _get_output_value
    outputs = self._get_stack_outputs(stack_name)
  File "/Users/seanrankine/.virtualenvs/project/lib/python2.7/site-packages/sceptre/resolvers/stack_output.py", line 71, in _get_stack_outputs
    outputs = response["Stacks"][0]["Outputs"]
KeyError: 'Outputs'
```

**Comment by jamesroutley** [comment] 2017-02-12 21:03
I feel like the way to fix this is to improve the exception thrown when this happens, rather than getting the resolver to wait: 

1. Waiting for a stack to complete doesn't feel like the job of the `stack_output` resolver. 
2. The use case for it is rare (a terminal crash, or a user ctrl-c'ing out of a launch).
3. Implementation isn't so easy - we wait for stacks to complete with `Stack._wait_for_completion`. I don't think a resolver has easy access to the `Stack` object representing the stack it's getting an output value from. 
4. `_wait_for_completion` currently prints out stack events as they happen. If this happens for an item of `sceptre_user_data` during a `generate-template` call, the printed events will mess up the template. We could get `_wait_for_completion` to not print out stack events, but I feel that waiting an arbitrary about of time with no indication to the user why we're waiting would be bad practice.

**Comment by theseanything** [comment] 2017-02-13 01:00
So I don't thinks a problem with resolvers its a problem with launch-env not waiting for a "CREATE_IN_PROGRESS" stack to finish, before launching a dependee stack.

From the copy of stdout you can see that `iam-instance-profile` stack was in "CREATE_IN_PROGRESS" and the `ec2-instances` was launched immediately.

**Comment by fitchxlin** [comment] 2017-09-13 18:40
Hi, 
I'm getting this message when creating a stack 

[2017-09-13 14:38:58] - sceptre.stack - nonprod/training-etlgroup - Creating stack
Enter MFA code:
Traceback (most recent call last):
  File "C:\Python27\Scripts\sceptre-script.py", line 11, in <module>
    load_entry_point('sceptre==1.1.2', 'console_scripts', 'sceptre')()
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\sceptre\cli.py", line 93, in decorated
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\sceptre\cli.py", line 243, in create_stack
    response = env.stacks[stack].create()
  File "c:\python27\lib\site-packages\sceptre\hooks\__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\sceptre\stack.py", line 194, in create
    "Parameters": self._format_parameters(self.parameters),
  File "c:\python27\lib\site-packages\sceptre\resolvers\__init__.py", line 72, in __get__
    return self.resolve_values(getattr(instance, self.name))
  File "c:\python27\lib\site-packages\sceptre\resolvers\__init__.py", line 91, in resolve_values
    attr[key] = value.resolve()
  File "c:\python27\lib\site-packages\sceptre\resolvers\stack_output.py", line 119, in resolve
    return self._get_output_value(stack_name, self.output_key)
  File "c:\python27\lib\site-packages\sceptre\resolvers\stack_output.py", line 34, in _get_output_value
    outputs = self._get_stack_outputs(stack_name)
  File "c:\python27\lib\site-packages\sceptre\resolvers\stack_output.py", line 71, in _get_stack_outputs
    outputs = response["Stacks"][0]["Outputs"]
KeyError: 'Outputs'

any ideas?

**Comment by robgodfrey-ft** [comment] 2018-01-30 15:28
This issue just bit me unfortunately on simple 2 stack scenario, whereby one stack uses the stack_output resolver to obtain an output variable to pass in as a parameter to the other. If both stacks don't exist to start with the stacks appear to be launched in the correct order but as previously stated, not waiting for the stack to CREATE_COMPLETE means resolution fails in this scenario. Running again once the stack has reached CREATE_COMPLETE then allows the dependent stack to launch cleanly. 

This does strike me as a somewhat hobbled dependency mechanism as it will never work if rebuilding an environment with stack_output based dependencies from scratch. To workaround I manage execution ordering manually. I have done this by grouping stacks into run first, run second, run third groups etc. and invoking launch for each group.

**Comment by ngfgrant** [comment] 2018-08-02 12:57
@robgodfrey-ft can I ask which version of sceptre you were using when this issue affected you? I am struggling to recreate it and think it might have been resolved as part of 970c118f2a18105e13e5bb370930f6e2de2ed674 but need to investigate further.  The commit that looks like it might have fixed this made it into the v1.20 release so if this has solved the problem any version since v1.20 might be working?

**Comment by robgodfrey-ft** [comment] 2018-08-02 16:46
Hi, 6 months on I don't know. I'll try and reproduce with 1.3.4 tomorrow. Will post steps to reproduce if I can.

**Comment by ngfgrant** [comment] 2018-08-03 08:14
@robgodfrey-ft Thanks - any pointers would be greatly appreciated.

**Comment by ngfgrant** [comment] 2018-11-21 23:43
closing see: https://github.com/cloudreach/sceptre/issues/422

**Closed by ngfgrant** 2018-11-21 23:43 UTC
Labels: bug, low priority
