### ISSUE TITLE
Cannot launch-env with config as top level

### ISSUE THREAD

**Issue by theseanything** [cloudreach/sceptre#159] opened 2017-07-05 17:09 UTC
Sceptre is unable to launch all environments within config folder (i.e. with config being the top level). 

For example:
```
config
├── config.yaml
├── env1
│   └── stack.yaml
└── env2
    └── stack.yaml
```
When running `sceptre launch-env .` sceptre attempts to launch both env1 and env2. However, cross-environment dependency resolution fails. This is because the full stack names are:
- `env1/stack`
- `env2/stack`

They don't share a common top level directory, which is required by the [_get_launch_dependencies](https://github.com/cloudreach/sceptre/blob/master/sceptre/environment.py#L284) function.

Hence at the moment we require all environments to be nested in a single top level folder within config to support cross-environment dependency resolution.
```
config
├── base
│   ├── test1
│   │   └── stack.yaml
│   └── test2
│       └── stack.yaml
└── config.yaml
```

**Comment by jamesroutley** [comment] 2017-07-06 00:17
Yep - this is caused by the way Sceptre initialises stacks. Currently, the top level environment is initialised, which initialises the tree of environments/stacks below it. If you try to resolve from a stack which isn't in that tree, you can't because the relevant stack object doesn't exist.

I have a feeling that our simplified Stack initialisers will help with this - you should be able to conjure up a stack with just its name, which will make implementing the above easy.

**Comment by rdkr** [comment] 2017-07-06 07:23
@theseanything, thanks for looking into this and creating the issue.

Any ETA on when the simplified stack initialisers will be implemented?

Is this restriction documented? I'm happy to create a PR adding it if not. 
This is what I used to test / report the issue to @theseanything, if it is of use: https://github.com/rdkr/sceptre-dependencies

**Comment by chandtailor1** [comment] 2017-07-06 08:56
I noticed an issue related to this. It's similar to your example Sean so thought it's better to put it here than create a new issue. Let's say "some stack" in env1 has a dependency on "some other stack" in env2 and you explicitly write this in the dependency section. If you try to launch env1 with "sceptre launch-env env1" it will not realise that it needs to launch env2 first and will give an error saying "some other stack" doesn't exist. I expected that it should know to launch env2 first especially if you have put it in the dependency section.

**Comment by chandtailor1** [comment] 2017-07-06 08:59
This also happens when they have a common top folder so even if you put them under base and try and launch with "sceptre launch-env base/env1" my use case will still fail

**Comment by mikkoc** [comment] 2017-10-18 13:20
Potentially related. I have the following folder structure:
```
config/component/sub-component/stacks.yaml
config/component/stack.yaml
```

I launch sceptre like this:
```
sceptre --var-file=environments/dev.yaml launch-env component
```

But sceptre completely ignores `stack.yaml` in the parent folder, and only creates/updates the sub-component stacks.

**Comment by stig** [comment] 2018-01-09 17:47
I have the same issue as @mikkoc. A workaround is, instead of structure like this:

```
config/eu-central-1/quux.yaml
config/eu-central-1/dev/foo.yaml
config/eu-central-1/test/bar.yaml
```

trying to `sceptre launch eu-central-1` will only launch the `foo` and `bar` stacks, completely omitting `quux`. One possible work-around is:

```
config/eu-central-1/common/quux.yaml
config/eu-central-1/dev/foo.yaml
config/eu-central-1/test/bar.yaml
```

However, that's annoying when `quux` already exists, and we're only now adding `foo` and `bar` 😬

**Comment by ngfgrant** [comment] 2018-11-21 23:42
Closing see: https://github.com/cloudreach/sceptre/issues/422

**Closed by ngfgrant** 2018-11-21 23:42 UTC
Labels: bug
